# Generated by Django 5.1.6 on 2025-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadd',
            name='experience',
            field=models.IntegerField(default=5),
        ),
    ]
