# Generated by Django 5.1.6 on 2025-03-07 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='status',
        ),
    ]
