# Generated by Django 5.1.6 on 2025-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
